[HTTP]
  listen_addr = ":2000"

[JWT]
  #用于产生JWT token的密码
  pstr = "%?*^`7Ax"
  #Token过期时间,单位分钟
  expire = 180

[GRPC]
  listen_addr = ":2001"
  certificate = "config/grpc.cert"
  key = "config/grpc.key"

[DB]
  user = "root"
  addr = "127.0.0.1:3306"
  pstr = "123456"
  # 数据库名
  db_name = "myaa"

# 日志配置
[LOG]
  # 日志级别: debug=5 info=4 warn=3 error=2
  level = 4
  # 单个日志文件大小（MB）
  max_size = 10
  # 日志轮转备份数
  max_backup = 5
